packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  - "docs/**"
  # all packages in subdirs of components/
  - "benches/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
