packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "packages/preact/utils"
  - "packages/react/utils"
  - "packages/react/runtime"
  # all packages in subdirs of components/
  - "docs/**"
  # extension package
  - "extension"
  # exclude packages that are inside test directories
  - "!**/test/**"
