# These command aliases are not final, may change
[alias]
# Alias to build actual plugin binary for the specified target.
build-wasip1 = "build --target wasm32-wasip1"
build-wasm32 = "build --target wasm32-unknown-unknown"
